# Generated by Django 5.2.17 on 2026-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_skill', models.CharField(max_length=255)),
                ('tingkat_keahlian', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
